# Generated by Django 4.2.1 on 2023-06-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_tbl_addloanname'),
        ('Admin', '0011_tbl_loan'),
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_loanapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('loannamedata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.tbl_addloanname')),
                ('memberdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_memberadding')),
            ],
        ),
    ]
