# Generated by Django 4.2.1 on 2023-06-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_tbl_loanapply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_loanapply',
            old_name='loannamedata',
            new_name='loan_name',
        ),
        migrations.RenameField(
            model_name='tbl_loanapply',
            old_name='memberdata',
            new_name='member_name',
        ),
    ]
