# Generated by Django 4.2.1 on 2023-06-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_tbl_loanapply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chittyjoin',
        ),
    ]
