# Generated by Django 4.2.1 on 2023-06-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0008_tbl_repaymentloan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_repaymentloan',
        ),
    ]
