# Generated by Django 4.2.1 on 2023-06-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_loan_name_tbl_proof_proof_name'),
        ('Member', '0012_tbl_repaymentloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_paymentchitty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chitty_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.tbl_chittyjoin')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_memberadding')),
            ],
        ),
    ]
