# Generated by Django 4.2.1 on 2023-06-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0014_tbl_relatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_relatives',
            name='refer_id',
            field=models.IntegerField(),
        ),
    ]
