# Generated by Django 4.2.1 on 2023-06-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0009_tbl_monthlycollection'),
        ('Member', '0015_alter_tbl_relatives_refer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_weeklycollectionpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.tbl_relatives')),
                ('weeklycollection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.tbl_weeklycollection')),
            ],
        ),
    ]
