# Generated by Django 4.2.1 on 2023-06-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_tbl_electionposition'),
        ('Member', '0019_tbl_scholarshipapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_weeklycollectionpayment',
            name='weeklycollection_id',
        ),
        migrations.AddField(
            model_name='tbl_weeklycollectionpayment',
            name='member_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.tbl_memberadding'),
        ),
        migrations.AlterField(
            model_name='tbl_weeklycollectionpayment',
            name='relative_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Member.tbl_relatives'),
        ),
    ]
