# Generated by Django 4.2.1 on 2023-06-20 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0009_tbl_monthlycollection'),
        ('Member', '0020_remove_tbl_weeklycollectionpayment_weeklycollection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_weeklycollectionpayment',
            name='weeklycollection_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.tbl_weeklycollection'),
        ),
    ]
