# Generated by Django 4.2.1 on 2023-06-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0021_tbl_weeklycollectionpayment_weeklycollection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_relatives',
            name='password',
            field=models.CharField(default=1234, max_length=50),
        ),
    ]
