# Generated by Django 4.2.1 on 2023-06-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0023_remove_tbl_chittyjoin_memberdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_chittyjoin',
            old_name='member_name',
            new_name='memberdata',
        ),
    ]
