# Generated by Django 4.2.1 on 2023-06-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0026_tbl_chittyjoin_tbl_paymentchitty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_paymentchitty',
        ),
    ]
