# Generated by Django 4.2.1 on 2023-06-27 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_tbl_electiondeclaration'),
        ('Member', '0029_tbl_electionapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.tbl_electionapply')),
                ('member_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.tbl_memberadding')),
                ('relative_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Member.tbl_relatives')),
            ],
        ),
    ]
