# Generated by Django 4.2.1 on 2023-07-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0034_tbl_chittyfunding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_chittyfunding',
            name='chitty_name',
            field=models.CharField(max_length=50),
        ),
    ]
