# Generated by Django 4.2.1 on 2023-07-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0035_alter_tbl_chittyfunding_chitty_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chittyfunding',
        ),
    ]
