# Generated by Django 4.2.1 on 2023-07-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0037_tbl_chittyfunding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
