# Generated by Django 4.2.1 on 2023-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0039_tbl_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='reply',
            field=models.CharField(default='Not viewed', max_length=200),
        ),
    ]
