# Generated by Django 4.2.1 on 2023-07-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0040_alter_tbl_complaint_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_repaymentloan',
            name='loanapply',
        ),
        migrations.RemoveField(
            model_name='tbl_repaymentloan',
            name='member',
        ),
        migrations.DeleteModel(
            name='tbl_loanapply',
        ),
        migrations.DeleteModel(
            name='tbl_repaymentloan',
        ),
    ]
