# Generated by Django 4.2.1 on 2023-07-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_tbl_electiondeclaration_status'),
        ('Finance', '0009_tbl_monthlycollection'),
        ('Member', '0041_remove_tbl_repaymentloan_loanapply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_loanapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('document', models.FileField(upload_to='Doc/')),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('loan_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.tbl_addloanname')),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_memberadding')),
                ('proof_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_proof')),
            ],
        ),
    ]
