# Generated by Django 4.2.1 on 2023-07-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_tbl_electiondeclaration_status'),
        ('Member', '0042_tbl_loanapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_repaymentloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanapply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.tbl_loanapply')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_memberadding')),
            ],
        ),
    ]
