# Generated by Django 4.2.1 on 2023-07-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0046_tbl_paymentchitty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_repaymentloan',
        ),
    ]
