# Generated by Django 4.2.1 on 2023-07-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0050_tbl_weeklycollectionpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_weeklycollectionpayment',
        ),
    ]
