# Generated by Django 4.2.1 on 2023-07-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0052_tbl_weeklycollectionpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_weeklycollectionpayment',
            old_name='repayment_date',
            new_name='payment_date',
        ),
    ]
