# Generated by Django 4.2.1 on 2023-07-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0053_rename_repayment_date_tbl_weeklycollectionpayment_payment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_monthlycollectionpayment',
        ),
    ]
