# Generated by Django 4.2.1 on 2023-07-15 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0009_tbl_monthlycollection'),
        ('Admin', '0033_tbl_electiondeclaration_status'),
        ('Member', '0054_delete_tbl_monthlycollectionpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_monthlycollectionpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_memberadding')),
                ('monthlycollection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.tbl_monthlycollection')),
            ],
        ),
    ]
