# Generated by Django 4.2.1 on 2023-07-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0055_tbl_monthlycollectionpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_scholarshipapply',
        ),
    ]
