# Generated by Django 4.2.1 on 2023-07-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0057_tbl_scholarshipapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_relatives',
            name='inactive',
            field=models.IntegerField(default=0),
        ),
    ]
