# Generated by Django 4.2.1 on 2023-06-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_tbl_addloanname'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_loancalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('startdate', models.DateField(max_length=50)),
                ('enddate', models.DateField(max_length=50)),
                ('no_installment', models.CharField(max_length=50)),
                ('loan_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.tbl_addloanname')),
            ],
        ),
    ]
