# Generated by Django 4.2.1 on 2023-06-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_tbl_loancalender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_loancalender',
        ),
    ]
