# Generated by Django 4.2.1 on 2023-06-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_loan_name_tbl_proof_proof_name'),
        ('Finance', '0005_tbl_loancalender'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chittycalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('startdate', models.DateField(max_length=50)),
                ('enddate', models.DateField(max_length=50)),
                ('no_installment', models.CharField(max_length=50)),
                ('chitty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.tbl_chitty')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_financehead')),
            ],
        ),
    ]
