# Generated by Django 4.2.1 on 2023-06-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_delete_tbl_relatives'),
        ('Finance', '0007_weeklycollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='weeklycollection',
            new_name='tbl_weeklycollection',
        ),
    ]
