# Generated by Django 4.2.1 on 2023-06-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_delete_tbl_relatives'),
        ('Finance', '0008_rename_weeklycollection_tbl_weeklycollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_monthlycollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_financehead')),
            ],
        ),
    ]
