from Member import views
from django.urls import path
app_name='Member'
urlpatterns = [
    path('homepage/', views.homepage,name="homepage"),

    path('myprofile/', views.myprofile,name="myprofile"),
    path('editprofile/', views.editprofile,name="editprofile"),
    path('changepassword/', views.changepassword,name="changepassword"),
    path('chittyview/', views.chittyview,name="chittyview"),
    path('ajaxchitty/',views.ajaxchitty,name="Ajaxchitty"),
    path('chittyjoin/<int:cid>', views.chittyjoin,name="chittyjoin"),
    path('chittystatusview/', views.chittystatusview,name="chittystatusview"),
    path('loanview/', views.loanview,name="loanview"),
    path('ajaxloan/',views.ajaxloan,name="Ajaxloan"),
    path('loanapply/<int:lnid>', views.loanapply,name="loanapply"),
    path('loanstatusview/', views.loanstatusview,name="loanstatusview"),
    path('loanpay/<int:lpid>', views.loanpay,name="loanpay"),
    path('repaymentloan/<int:lid>', views.repaymentloan,name="repaymentloan"),
    path('chittypay/<int:cpid>', views.chittypay,name="chittypay"),
    path('paymentchitty/<int:cid>', views.paymentchitty,name="paymentchitty"),
    path('relatives/', views.relatives,name="relatives"),
    path('Ajaxrelation/', views.Ajaxrelation,name="Ajaxrelation"),
    path('viewweeklycollection/', views.viewweeklycollection,name="viewweeklycollection"),
    path('viewmonthlycollection/', views.viewmonthlycollection,name="viewmonthlycollection"),
    #path('designpayment/', views.designpayment,name="designpayment"),
    path('paysucessful/', views.paysucessful,name="paysucessful"),
    path('runpayment/', views.runpayment,name="runpayment"),
    path('logout/', views.logout,name="logout"),
    path('weeklycollectionpayment/<int:wid>', views.weeklycollectionpayment,name="weeklycollectionpayment"),
    path('monthlycollectionpayment/<int:mcid>', views.monthlycollectionpayment,name="monthlycollectionpayment"),
    
    path('scholarshipview/', views.scholarshipview,name="scholarshipview"),
    path('ajaxscholarship/',views.ajaxscholarship,name="Ajaxscholarship"),
    path('scholarshipapply/<int:said>', views.scholarshipapply,name="scholarshipapply"),
    path('scholarshipstatus/', views.scholarshipstatus,name="scholarshipstatus"),
    path('deleterelative/<int:rdid>', views.deleterelative,name="deleterelative"),
    path('viewelection/<int:eid>', views.viewelection,name="viewelection"),
    path('electionapply/<int:eaid>', views.electionapply,name="electionapply"),
    path('electionapplystatusview/', views.electionapplystatusview,name="electionapplystatusview"),
    path('viewcandidate/<int:ecid>', views.viewcandidate,name="viewcandidate"),
    path('votenow/<int:cvid>', views.votenow,name="votenow"),
    path('vote/<int:vid>', views.vote,name="vote"),
     path('viewevents/', views.viewevents,name="viewevents"),
     path('complaint/', views.complaint,name="complaint"),
     path('feedback/', views.feedback,name="feedback"),
      path('chittyfunding/', views.chittyfunding,name="chittyfunding"),
      path('chittyfundingstatusview/', views.chittyfundingstatusview,name="chittyfundingstatusview"),
    path('loanreport/', views.loanreport,name="loanreport"),
    path('chittyreport/', views.chittyreport,name="chittyreport"),
     path('scholarshipreport/', views.scholarshipreport,name="scholarshipreport"),
]