# Generated by Django 4.2.1 on 2023-05-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_scheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_financehead',
        ),
    ]
