# Generated by Django 4.2.1 on 2023-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_tbl_memberadding_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=50)),
            ],
        ),
    ]
