# Generated by Django 4.2.1 on 2023-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=50)),
            ],
        ),
    ]
