# Generated by Django 4.2.1 on 2023-06-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_proof',
            old_name='loan_name',
            new_name='proof_name',
        ),
    ]
