# Generated by Django 4.2.1 on 2023-06-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_loan_name_tbl_proof_proof_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_relationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=50)),
            ],
        ),
    ]
