# Generated by Django 4.2.1 on 2023-06-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_relatives'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_relatives',
        ),
    ]
