# Generated by Django 4.2.1 on 2023-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_delete_tbl_relatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scholarshiptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_type', models.CharField(max_length=50)),
            ],
        ),
    ]
