# Generated by Django 4.2.1 on 2023-06-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_tbl_scholarshipname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_scholarshipname',
            old_name='proof_name_type',
            new_name='proof_name',
        ),
    ]
