# Generated by Django 4.2.1 on 2023-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_rename_proof_name_type_tbl_scholarshipname_proof_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_electionposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_position', models.CharField(max_length=50)),
            ],
        ),
    ]
