# Generated by Django 4.2.1 on 2023-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_alter_tbl_memberadding_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_memberadding',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
