# Generated by Django 4.2.1 on 2023-06-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_electiondeclaration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_electiondeclaration',
        ),
    ]
