# Generated by Django 4.2.1 on 2023-06-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_tbl_electiondeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('event_date', models.DateField(max_length=50)),
            ],
        ),
    ]
